import { ClusterCard, type ClusterProps } from "./components/ClusterCard";
import { Search, Globe } from "lucide-react";
import { Suspense } from "react";

// Fetch the static cache generated by the python backend
async function getData() {
  try {
    const url = "https://storage.googleapis.com/aqua-news-cache/latest.json";
    const res = await fetch(url, { next: { revalidate: 3600 } });

    if (!res.ok) {
      console.warn("Failed to fetch news data from GCS during build/runtime.");
      return { clusters: [], cluster_count: 0, fetched_at: new Date().toISOString() };
    }
    return res.json();
  } catch (err) {
    console.warn("Error fetching news data:", err);
    return { clusters: [], cluster_count: 0, fetched_at: new Date().toISOString() };
  }
}

export default async function Home() {
  const data = await getData();
  const clusters = data.clusters || [];

  // Basic server-side filtering setup (in a real app we'd use URL searchParams for active filtering) //
  // For now, we will render all clusters and the user can scroll, replicating the static beauty of an editorial.

  return (
    <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20">
      {/* Header */}
      <header className="mb-16 border-b-4 border-stone-900 pb-8">
        <div className="flex justify-between items-end">
          <div>
            <h1 className="text-4xl md:text-5xl font-serif font-bold text-stone-900 tracking-tight">
              AQUA NEWS
            </h1>
            <p className="mt-4 text-stone-500 font-mono text-xs uppercase tracking-[0.2em] max-w-lg">
              Multi-source clustering • Bias spectrum analysis • AI-free
              editorial
            </p>
          </div>
          <div className="text-right hidden sm:block">
            <p className="font-mono text-[10px] text-stone-400 uppercase tracking-widest mb-1">
              Last Updated
            </p>
            <p className="font-mono text-xs text-stone-600 font-semibold">
              {new Date(data.fetched_at).toLocaleDateString("en-US", {
                month: "short",
                day: "numeric",
                year: "numeric",
                hour: "2-digit",
                minute: "2-digit",
              })}
            </p>
          </div>
        </div>
      </header>

      {/* Stats Bar */}
      <div className="flex flex-wrap gap-8 py-4 mb-12 border-b border-stone-200 font-mono text-[11px] uppercase tracking-wider text-stone-500">
        <div className="flex items-center gap-2">
          <Globe className="w-4 h-4 text-stone-900" />
          <span className="text-stone-900 font-bold">
            {clusters.length}
          </span>{" "}
          Clusters
        </div>
        <div>
          <span className="text-stone-900 font-bold">
            {data.cluster_count || 0}
          </span>{" "}
          Sources Analyzed
        </div>
      </div>

      {/* Grid */}
      <div className="flex flex-col gap-12 md:gap-16">
        {clusters.length === 0 ? (
          <div className="text-center py-20 text-stone-400 font-mono">
            Waiting for daily ingest pipeline...
          </div>
        ) : (
          clusters.map((cluster: any, idx: number) => (
            <ClusterCard key={idx} data={cluster} />
          ))
        )}
      </div>

      {/* Footer */}
      <footer className="mt-20 pt-8 border-t border-stone-200 text-center text-stone-400 font-mono text-[10px] uppercase tracking-widest pb-12">
        AQUA NEWS • Unbiased, automated clustering
      </footer>
    </main>
  );
}
