import { ClientHome } from "./components/ClientHome";

// Fetch the static cache generated by the python backend
async function getData() {
  try {
    const bucket = process.env.GCS_BUCKET;
    const blob = process.env.GCS_BLOB || "latest.json";
    if (!bucket) {
      console.error("GCS_BUCKET env var is not set");
      return { clusters: [], cluster_count: 0, fetched_at: new Date().toISOString() };
    }
    const url = `https://storage.googleapis.com/${bucket}/${blob}`;
    const res = await fetch(url, { next: { revalidate: 3600 } });

    if (!res.ok) {
      console.warn("Failed to fetch news data from GCS during build/runtime.");
      return { clusters: [], cluster_count: 0, fetched_at: new Date().toISOString() };
    }
    return res.json();
  } catch (err) {
    console.warn("Error fetching news data:", err);
    return { clusters: [], cluster_count: 0, fetched_at: new Date().toISOString() };
  }
}

export default async function Home() {
  const data = await getData();
  return <ClientHome data={data} />;
}
